export const navItems = [
  { href: "/platform/tenants", label: "Platform", icon: "shield", superOnly: true },
  { href: "/platform/billing", label: "Platform Billing", icon: "credit", superOnly: true },
  { href: "/platform/usage", label: "Platform Usage", icon: "chart", superOnly: true },
  { href: "/platform/security", label: "Platform Security", icon: "shield-check", superOnly: true },
  { href: "/platform/support", label: "Platform Support", icon: "life-buoy", superOnly: true },
  { href: "/analytics", label: "Analytics", icon: "chart" },
  { href: "/records", label: "Records", icon: "table" },
  { href: "/review", label: "Review", icon: "flag", viewerHidden: true },
  { href: "/staff", label: "Staff", icon: "users", viewerHidden: true },
  { href: "/compliance", label: "Compliance", icon: "table", viewerHidden: true },
  { href: "/support", label: "Support", icon: "life-buoy" },
  { href: "/requirements", label: "Requirements", icon: "shield", viewerHidden: true, managerHidden: true },
  { href: "/devices", label: "Devices", icon: "cpu", viewerHidden: true, managerHidden: true },
  { href: "/uploads", label: "Uploads", icon: "cloud" },
  { href: "/sources", label: "Sources", icon: "plug", viewerHidden: true, managerHidden: true },
  { href: "/plan", label: "Manage plan", icon: "credit", viewerHidden: true, managerHidden: true },
  { href: "/profile", label: "Profile", icon: "user" },
  { href: "/invite", label: "Invite", icon: "users", viewerHidden: true },
  { href: "/logout", label: "Logout", icon: "exit" }
];
