// <auto-generated />
using System;
using CertiWatch.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CertiWatch.Api.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20251220081500_FieldsJsonToText")]
partial class FieldsJsonToText
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("ActorId")
                    .HasColumnType("uuid");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("MetaJson")
                    .HasColumnType("jsonb");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.ToTable("AuditLogs");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.BillingInvoice", b =>
            {
                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<string>("StripeInvoiceId")
                    .HasColumnType("text");

                b.Property<decimal>("AmountDue")
                    .HasColumnType("numeric");

                b.Property<decimal>("AmountPaid")
                    .HasColumnType("numeric");

                b.Property<DateTime?>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Currency")
                    .HasColumnType("text");

                b.Property<DateTime?>("InvoiceDateUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PdfUrl")
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .HasColumnType("text");

                b.Property<string>("HostedInvoiceUrl")
                    .HasColumnType("text");

                b.HasKey("TenantId", "StripeInvoiceId");

                b.HasIndex("StripeInvoiceId", "TenantId")
                    .IsUnique();

                b.ToTable("BillingInvoices");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.CourseRule", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("CourseName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int?>("DefaultValidityMonths")
                    .HasColumnType("integer");

                b.Property<bool>("IsOneTime")
                    .HasColumnType("boolean");

                b.Property<bool>("IsRenewable")
                    .HasColumnType("boolean");

                b.Property<string>("IssuerOverride")
                    .HasColumnType("text");

                b.Property<string>("MatchRegex")
                    .HasColumnType("text");

                b.Property<string>("Tag")
                    .HasColumnType("text");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("TenantId", "CourseName");

                b.ToTable("CourseRules");

                b.HasData(
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000001"),
                        CourseName = "First Aid",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 36,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000002"),
                        CourseName = "Fire Safety",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 12,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000003"),
                        CourseName = "Food Hygiene Level 2",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 12,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000004"),
                        CourseName = "Manual Handling",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 24,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000005"),
                        CourseName = "Safeguarding Adults",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 24,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000006"),
                        CourseName = "GDPR Awareness",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 12,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000007"),
                        CourseName = "Infection Control",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 12,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000008"),
                        CourseName = "Health and Safety Induction",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 36,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000009"),
                        CourseName = "Equality and Diversity",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 36,
                        IsRenewable = true
                    },
                    new
                    {
                        Id = new Guid("00000000-0000-0000-0000-000000000010"),
                        CourseName = "COSHH Awareness",
                        CreatedAt = new DateTime(2025, 12, 20, 8, 15, 0, 0, DateTimeKind.Utc),
                        DefaultValidityMonths = 12,
                        IsRenewable = true
                    });
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Device", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("DeviceToken")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("OperatingSystem")
                    .HasColumnType("text");

                b.Property<Guid?>("SourceId")
                    .HasColumnType("uuid");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("EnrolledAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("LastSeenAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("TenantId", "DeviceToken")
                    .IsUnique();

                b.ToTable("Devices");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Document", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime?>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("CreatedByUserId")
                    .HasColumnType("uuid");

                b.Property<string>("DocumentType")
                    .HasColumnType("text");

                b.Property<decimal?>("ExtractionConfidence")
                    .HasColumnType("numeric");

                b.Property<string>("FileHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("MimeType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("ProcessedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("ProcessingStatus")
                    .HasColumnType("integer");

                b.Property<string>("PathOrUrl")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("SourceId")
                    .HasColumnType("uuid");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("VendorId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("ProcessingStatus", "CreatedAt")
                    .HasDatabaseName("idx_documents_status_created");

                b.HasIndex("CreatedByUserId");

                b.ToTable("Documents");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Reminder", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("RecordId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("ScheduledFor")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("SentAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("RecordId");

                b.ToTable("Reminders");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Record", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("CreatedByUserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<string>("DocumentType")
                    .HasColumnType("text");

                b.Property<bool>("ExpiryDerived")
                    .HasColumnType("boolean");

                b.Property<DateOnly?>("ExpiryDate")
                    .HasColumnType("date");

                b.Property<string>("FieldsJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal?>("ExtractionConfidence")
                    .HasColumnType("numeric");

                b.Property<decimal>("Confidence")
                    .HasColumnType("numeric");

                b.Property<DateOnly?>("IssueDate")
                    .HasColumnType("date");

                b.Property<string>("Issuer")
                    .HasColumnType("text");

                b.Property<int>("ProcessingStatus")
                    .HasColumnType("integer");

                b.Property<string>("ReviewNotes")
                    .HasColumnType("text");

                b.Property<string>("ReviewReason")
                    .HasColumnType("text");

                b.Property<Guid?>("ReviewedBy")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("ReviewedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CourseName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("StaffName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("CreatedByUserId");

                b.HasIndex("DocumentId");

                b.HasIndex("ExpiryDate");

                b.HasIndex("StaffName")
                    .HasMethod("gin")
                    .HasOperators(new[] { "gin_trgm_ops" });

                b.HasIndex("CourseName")
                    .HasMethod("gin")
                    .HasOperators(new[] { "gin_trgm_ops" });

                b.HasIndex("TenantId");

                b.ToTable("Records");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Source", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ConfigJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("TenantId");

                b.ToTable("Sources");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.SourceSecret", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime?>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("SourceId")
                    .HasColumnType("uuid");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("TenantId", "SourceId", "Key")
                    .IsUnique();

                b.ToTable("SourceSecrets");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("BillingEmail")
                    .HasColumnType("text");

                b.Property<DateTime?>("CancelAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("CurrentPeriodEndUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Plan")
                    .HasColumnType("text");

                b.Property<string>("StripeCustomerId")
                    .HasColumnType("text");

                b.Property<string>("StripeSubscriptionId")
                    .HasColumnType("text");

                b.Property<string>("SubscriptionStatus")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Tenants");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.UploadRequest", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid?>("CreatedByUserId")
                    .HasColumnType("uuid");

                b.Property<string>("CourseName")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ExpiryHint")
                    .HasColumnType("text");

                b.Property<string>("FilePath")
                    .HasColumnType("text");

                b.Property<string>("OriginalFileName")
                    .HasColumnType("text");

                b.Property<string>("StaffEmail")
                    .HasColumnType("text");

                b.Property<string>("StaffName")
                    .HasColumnType("text");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("UsedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("TenantId", "Token")
                    .IsUnique();

                b.HasIndex("CreatedByUserId");

                b.ToTable("UploadRequests");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid?>("InvitedByUserId")
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("TenantId", "Email")
                    .IsUnique();

                b.ToTable("Users");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Document", b =>
            {
                b.HasOne("CertiWatch.Api.Domain.Entities.Source", "Source")
                    .WithMany()
                    .HasForeignKey("SourceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CertiWatch.Api.Domain.Entities.Vendor", "Vendor")
                    .WithMany()
                    .HasForeignKey("VendorId");

                b.Navigation("Source");

                b.Navigation("Vendor");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Reminder", b =>
            {
                b.HasOne("CertiWatch.Api.Domain.Entities.Record", "Record")
                    .WithMany("Reminders")
                    .HasForeignKey("RecordId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Record");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Record", b =>
            {
                b.HasOne("CertiWatch.Api.Domain.Entities.Document", "Document")
                    .WithMany("Records")
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Document");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Source", b =>
            {
                b.HasOne("CertiWatch.Api.Domain.Entities.Tenant", null)
                    .WithMany()
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.SourceSecret", b =>
            {
                b.HasOne("CertiWatch.Api.Domain.Entities.Source", null)
                    .WithMany("Secrets")
                    .HasForeignKey("SourceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.UploadRequest", b =>
            {
                b.HasOne("CertiWatch.Api.Domain.Entities.Tenant", null)
                    .WithMany()
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.User", b =>
            {
                b.HasOne("CertiWatch.Api.Domain.Entities.Tenant", null)
                    .WithMany()
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Document", b =>
            {
                b.Navigation("Records");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Record", b =>
            {
                b.Navigation("Reminders");
            });

        modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Source", b =>
            {
                b.Navigation("Secrets");
            });
#pragma warning restore 612, 618
    }
}
