// <auto-generated />
using System;
using CertiWatch.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CertiWatch.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207105015_AddDocumentTypeAndExtractionConfidence")]
    partial class AddDocumentTypeAndExtractionConfidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.CourseRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultValidityMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRenewable")
                        .HasColumnType("boolean");

                    b.Property<string>("IssuerOverride")
                        .HasColumnType("text");

                    b.Property<string>("MatchRegex")
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CourseName");

                    b.ToTable("CourseRules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CourseName = "First Aid",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4726),
                            DefaultValidityMonths = 36,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CourseName = "Fire Safety",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4750),
                            DefaultValidityMonths = 12,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CourseName = "Food Hygiene Level 2",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4758),
                            DefaultValidityMonths = 12,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CourseName = "Manual Handling",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4763),
                            DefaultValidityMonths = 24,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CourseName = "Safeguarding Adults",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4769),
                            DefaultValidityMonths = 24,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CourseName = "GDPR Awareness",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4787),
                            DefaultValidityMonths = 12,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CourseName = "Infection Control",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4797),
                            DefaultValidityMonths = 12,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CourseName = "Health and Safety Induction",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4803),
                            DefaultValidityMonths = 36,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CourseName = "Equality and Diversity",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(4809),
                            DefaultValidityMonths = 36,
                            IsOneTime = false,
                            IsRenewable = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CourseName = "COSHH Awareness",
                            CreatedAt = new DateTime(2025, 12, 7, 10, 50, 13, 10, DateTimeKind.Utc).AddTicks(5019),
                            DefaultValidityMonths = 12,
                            IsOneTime = false,
                            IsRenewable = true
                        });
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<decimal?>("ExtractionConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathOrUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("VendorId");

                    b.HasIndex("ProcessingStatus", "CreatedAt")
                        .HasDatabaseName("idx_documents_status_created");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("ExpiryDerived")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ExtractionConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .HasColumnType("text");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CourseName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("CourseName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("StaffName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StaffName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("StaffName"), new[] { "gin_trgm_ops" });

                    b.ToTable("Records");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.UploadRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExpiryHint")
                        .HasColumnType("date");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<string>("StaffEmail")
                        .HasColumnType("text");

                    b.Property<string>("StaffName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Token")
                        .IsUnique();

                    b.ToTable("UploadRequests");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HintsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatternsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.CourseRule", b =>
                {
                    b.HasOne("CertiWatch.Api.Domain.Entities.Tenant", null)
                        .WithMany("Rules")
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Device", b =>
                {
                    b.HasOne("CertiWatch.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Document", b =>
                {
                    b.HasOne("CertiWatch.Api.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertiWatch.Api.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Source");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Record", b =>
                {
                    b.HasOne("CertiWatch.Api.Domain.Entities.Document", "Document")
                        .WithMany("Records")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("CertiWatch.Api.Domain.Entities.Record", "Record")
                        .WithMany("Reminders")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Source", b =>
                {
                    b.HasOne("CertiWatch.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("CertiWatch.Api.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Document", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Record", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("CertiWatch.Api.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
